# Generated by Django 5.2.4 on 2025-08-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0002_labellingmachine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labellingmachine',
            name='content',
        ),
        migrations.RemoveField(
            model_name='labellingmachine',
            name='price',
        ),
        migrations.AlterField(
            model_name='labellingmachine',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='labellingmachine',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
