# Generated by Django 5.2.4 on 2025-09-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0003_remove_labellingmachine_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SealingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
