# Generated by Django 5.2.4 on 2025-09-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0013_ancillaryunit_conveyorsystem_machinespare_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AncillaryUnit',
            new_name='Ancillaryunits',
        ),
        migrations.RenameModel(
            old_name='ConveyorSystem',
            new_name='Conveyorsystems',
        ),
        migrations.RenameModel(
            old_name='MachineSpare',
            new_name='Machinespares',
        ),
        migrations.RenameModel(
            old_name='MechanicalSeal',
            new_name='Mechanicalseals',
        ),
        migrations.RenameModel(
            old_name='Nozzle',
            new_name='Nozzles',
        ),
        migrations.RenameModel(
            old_name='RubberComponent',
            new_name='Rubbercomponents',
        ),
    ]
