# Generated by Django 5.2.4 on 2025-09-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0014_rename_ancillaryunit_ancillaryunits_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machineenquiry',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='machineenquiry',
            name='machinery',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
