# Generated by Django 5.2.4 on 2025-09-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0015_alter_machineenquiry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineenquiry',
            name='cust_constraints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='cust_target_specs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='cust_use_case',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='rev_material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='rev_part_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='rev_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='rev_tolerance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='service_type',
            field=models.CharField(choices=[('general', 'General Enquiry'), ('customization', 'Design Customization'), ('reverse', 'Reverse Engineering')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='source_service',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
