# Generated by Django 5.2.4 on 2025-10-02 05:32

import django.db.models.deletion
import sehdev.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0016_machineenquiry_cust_constraints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineenquiry',
            name='cust_constraints',
        ),
        migrations.RemoveField(
            model_name='machineenquiry',
            name='cust_target_specs',
        ),
        migrations.RemoveField(
            model_name='machineenquiry',
            name='cust_use_case',
        ),
        migrations.RemoveField(
            model_name='machineenquiry',
            name='rev_part_name',
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='cust_deadline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='cust_format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='cust_integration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='cust_line_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='cust_pain_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='cust_plc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='cust_throughput',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='rev_conditions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='rev_docs',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='rev_part',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='rev_sample',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='rev_urgency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='machineenquiry',
            name='service_type',
            field=models.CharField(choices=[('general', 'General Enquiry'), ('customization', 'Design Customization'), ('reverse', 'Reverse Engineering')], default='general', max_length=32),
        ),
        migrations.CreateModel(
            name='EnquiryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=sehdev.models.enquiry_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='sehdev.machineenquiry')),
            ],
        ),
    ]
