# Generated by Django 5.2.4 on 2025-10-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0017_remove_machineenquiry_cust_constraints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineenquiry',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload drawing / photo / reference document', null=True, upload_to='enquiries/'),
        ),
    ]
