# Generated by Django 5.2.4 on 2025-12-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0018_machineenquiry_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='washing_units/')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('is_new', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='enquiryattachment',
            name='file',
            field=models.FileField(upload_to='enquiries/%Y/%m'),
        ),
    ]
