# Generated by Django 5.2.4 on 2025-12-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0019_washingunit_alter_enquiryattachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabellingComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Component ka naam (e.g. Label dispensing assemblies)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
