# Generated by Django 5.2.4 on 2025-12-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0020_labellingcomponent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labellingcomponent',
            name='is_active',
        ),
        migrations.AddField(
            model_name='labellingcomponent',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labellingcomponent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labellingcomponent',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='labellingcomponent',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
