# Generated by Django 5.2.4 on 2025-12-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0024_conveyorcomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Needles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='nozzles',
            name='finish',
            field=models.CharField(default='Mirror Polish', max_length=100, null=True),
        ),
    ]
