# Generated by Django 5.2.4 on 2025-12-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0025_needles_nozzles_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nozzles',
            name='finish',
            field=models.CharField(default='Mirror Polish', max_length=100),
        ),
    ]
