# Generated by Django 5.2.4 on 2025-12-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0026_alter_nozzles_finish'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='products/change-parts/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Machinespares',
        ),
    ]
