# Generated by Django 5.2.4 on 2025-12-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0028_misc_pharmatool_delete_accessory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConveyorBelt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
