# Generated by Django 5.2.4 on 2025-12-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0030_wearstrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineenquiry',
            name='refurb_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='refurb_machine_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='refurb_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineenquiry',
            name='refurb_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machineenquiry',
            name='service_type',
            field=models.CharField(choices=[('general', 'General Enquiry'), ('customization', 'Design Customization'), ('reverse', 'Reverse Engineering'), ('refurbishment', 'Product Refurbishment')], default='general', max_length=32),
        ),
    ]
