# Generated by Django 5.2.4 on 2025-12-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0031_machineenquiry_refurb_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineenquiry',
            name='service_type',
            field=models.CharField(blank=True, choices=[('general', 'General Enquiry'), ('customization', 'Design Customization'), ('reverse', 'Reverse Engineering'), ('refurbishment', 'Product Refurbishment')], max_length=32, null=True),
        ),
    ]
