# Generated by Django 5.2.4 on 2026-01-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0032_alter_machineenquiry_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleHandlingFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='fixtures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='changeparts',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='conveyorcomponent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fillingcomponent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='labellingcomponent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='misc',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='nozzles',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='pharmatool',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sealingcomponent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='washingunit',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='washingunit',
            name='short_description',
        ),
    ]
