# Generated by Django 5.2.4 on 2026-01-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehdev', '0034_sealinghead'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashingComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='washingunit',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='washingunit',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='washingunit',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
