# Generated by Django 5.2.4 on 2025-09-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sehdev', '0015_alter_machineenquiry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineEnquiryAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Machine enquiry',
                'verbose_name_plural': 'Machine enquiries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sehdev.machineenquiry',),
        ),
    ]
