# Generated by Django 5.2.4 on 2025-09-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sehdev', '0015_alter_machineenquiry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sehdev.accessory',),
        ),
        migrations.CreateModel(
            name='AncillaryunitsAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Ancillary unit',
                'verbose_name_plural': 'Ancillary units',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sehdev.ancillaryunits',),
        ),
        migrations.CreateModel(
            name='ConveyorsystemsAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Conveyor system',
                'verbose_name_plural': 'Conveyor systems',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sehdev.conveyorsystems',),
        ),
        migrations.CreateModel(
            name='FillingMachineAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Filling machine',
                'verbose_name_plural': 'Filling machines',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sehdev.fillingmachine',),
        ),
        migrations.CreateModel(
            name='LabellingMachineAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Labelling machine',
                'verbose_name_plural': 'Labelling machines',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sehdev.labellingmachine',),
        ),
        migrations.CreateModel(
            name='MachinesparesAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Machine spare',
                'verbose_name_plural': 'Machine spares',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sehdev.machinespares',),
        ),
        migrations.CreateModel(
            name='MechanicalsealsAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Mechanical seal',
                'verbose_name_plural': 'Mechanical seals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sehdev.mechanicalseals',),
        ),
        migrations.CreateModel(
            name='NozzlesAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Nozzle / Needle',
                'verbose_name_plural': 'Nozzles & Needles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sehdev.nozzles',),
        ),
        migrations.CreateModel(
            name='RubbercomponentsAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Rubber component',
                'verbose_name_plural': 'Rubber components',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sehdev.rubbercomponents',),
        ),
        migrations.CreateModel(
            name='SealingMachineAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Sealing machine',
                'verbose_name_plural': 'Sealing machines',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sehdev.sealingmachine',),
        ),
    ]
