# Generated by Django 5.2.4 on 2025-12-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_machinesparesadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessoryAdmin',
        ),
    ]
